### ISSUE TITLE
Prueba APK en dispositivo físico Android 

### ISSUE THREAD

**Issue by Yoel1515** [Centinela-RR/Custodes#11]
### Pasos para permitir la instalación
- Entrar a Playstore
- Foto de perfil
- Administrar dispositivo y apps
- Análisis de Play Protect
- Configuración
- Desactivar análisis de Play Protect

**Comment by 2021030063** [comment]
Plan es, obtener un apk, lo subes a [releases](https://github.com/Centinela-RR/Custodes/releases/new) con esta info:
tag: v0.0.1-prealpha
target: app-prealpha
Set as pre-release
Create a discussion for this release: Feedback
<img width="543" alt="How to make releases" src="https://github.com/Centinela-RR/Custodes/assets/152040336/0ef140f7-48e3-4493-9374-61e4957ea213">

**Comment by 2021030063** [comment]
Y @Centinela-RR/android-test should help, pero sólo están @Oliasaew y tú jaja (excluyéndome), entonces no sé si quieras agregar a alguien al equipo de pruebas de android jajaj

**Comment by 2021030063** [comment]
@202100013 Please get on this lol :)

**Comment by Yoel1515** [comment]
tu también tienes la matrícula JAJAJ

**Comment by 2021030063** [comment]
Al menos tengo una imagen que nadie usaría y me identifica UnU

**Comment by Yoel1515** [comment]
Ya se como hacer el APK lo que pasa es que no funciona el APK luego lo cheque en el emulador y tampoco funcionaba , se movio algo jhona? si solo fue el nombre y el id
la aplicacion se cierra y antes si jalaba

**Comment by 2021030063** [comment]
Lemme check the files changed and get back to you

**Comment by Yoel1515** [comment]
No me permite hace un commit en app-prealpha 
????

**Comment by 2021030063** [comment]
shit sorry lmao

**Comment by 2021030063** [comment]
should be fixed now

**Comment by 2021030063** [comment]
@Yoel1515 pls how to fix?

**Comment by Yoel1515** [comment]
debe que reconocer el creador de la App?

**Comment by 2021030063** [comment]
Ya listo con los pasos para desactivar este lío en el inicio de la issue, ty

**Comment by 2021030063** [comment]
Resultado: Aplicación funcional, líos para instalar tratados, la vida es buena

**Comment by 2021030063** [comment]
AYOO?? Por qué los títulos no están centrados en Android?
![PHOTO-2024-01-16-13-09-19](https://github.com/Centinela-RR/Custodes/assets/152040336/35421eb6-90b8-4d0b-80e1-d1157998addf)
![IMG_4460](https://github.com/Centinela-RR/Custodes/assets/152040336/562a49b4-3426-4ae5-b974-221359120de4)

**Comment by Yoel1515** [comment]
lei que asi lo tiene flutter por defecto en los diseños

**Comment by 2021030063** [comment]
Alineado a la izquierda en Android y centrado en iOS?

**Comment by Yoel1515** [comment]
Asies 
que procede ?

**Comment by 2021030063** [comment]
Dejarlo así, si flutter lo caga ig :/
So yep, not an issue I GUESS ://///
