### ISSUE TITLE
Comunicación con db

### ISSUE THREAD

**Issue by 2021030063** [Centinela-RR/Custodes#19]
Plática e interacción con la raza de @Centinela-RR/db para establecer:
- Funcionamiento adecuado de la app
- Campos necesarios
- Datos a utilizar
- Datos manipulables y cambiables por interacción con el usuario

Si algo más surge, pues también lol

**Comment by Yoel1515** [comment]
Que procede o que hago o donde lo hago? Mañana se habla ?

**Comment by 2021030063** [comment]
yep, tomowwow, cuando ya esté clara la vista y estemos en contacto con @202100013 porque no va a responder por aquí jajAAA :(

**Comment by 2021030063** [comment]
Ya se supone que sabe @Centinela-RR/db lo que van a hacer, sólo falta hagan un mockup de las tablas a utilizar y, yea...
