### ISSUE TITLE
Conexión con la db de Firebase

### ISSUE THREAD

**Issue by 2021030063** [Centinela-RR/Custodes#20]
Enlace a Firebase [aquí](https://console.firebase.google.com/project/custodes-97a6a/settings/general/).
Hay que:
- Conectar ambas apps a la db

**Comment by 2021030063** [comment]
Cuál db usamos de Firebase?
Asumo que Realtime Database sería mejor, pero no sé porque Firestore no suena nada mal aaa
Check here: [Comparación](https://firebase.google.com/docs/firestore/rtdb-vs-firestore)

**Comment by Yoel1515** [comment]
pff por lo que veo te la pintan mas bonito con el Firestore jajaja

**Comment by Yoel1515** [comment]
pero la realtime es la que tiene menos latencia es como k aaaa nose la vdd

**Comment by 2021030063** [comment]
<img width="999" alt="Firestore" src="https://github.com/Centinela-RR/Custodes/assets/152040336/fe6ad70e-5141-4e00-afaf-389a88b10d6c">
<img width="900" alt="Realtime" src="https://github.com/Centinela-RR/Custodes/assets/152040336/87bcb0e2-1391-4404-85dc-869ec3413a58">
Entonces, Firestore cobra por interacciones con la db, mientras que Realtime cobra por GB de almacenamiento y descargado, pero tiene límite de conexiones simultáneas, por lo que si logramos optimizar los datos guardados y las operaciones realizadas junto a la raza de @Centinela-RR/db, digo que conviene más Realtime si logramos hacer que cada reporte nuevo (o cada 5 segundos o algo así, idk) llame una nueva conexión a la db, reciba y/o envíe información y cierre la conexión

***

### En resumen:
Si logramos optimizar las conexiones y reducirlas a la cantidad mínima, optimizar la db y las operaciones realizadas en ella, conviene usar Realtime; de lo contrario ir a Firestore

**Comment by Yoel1515** [comment]
okey tons el realtime mejor aver si se logra

**Comment by Yoel1515** [comment]
una pregunta jhoona cuando creaste lo de firebase agregaste el Id del proyecto vdd

**Comment by 2021030063** [comment]
Iba a hacer solo la pantalla de inicio pero no supe, así que preparé el proyecto en firebase y con flutter le puse "agregar componentes" básicamente, y pues, yea...
Sólo eso jajaaaa

**Comment by Yoel1515** [comment]
Bañes pues ya vi que es una movida mucha wea conectarla lo haré por CLI mañana como quiera ya anduve viendo

**Comment by Yoel1515** [comment]
Bueno pss esto ya quedaria no ?

**Comment by 2021030063** [comment]
Yep, deja checo los detalles de Firestore y agrego el plugin

**Comment by 2021030063** [comment]
Ya tenemos la db, I repeat, ya tenemos la db
[Db here](https://console.firebase.google.com/u/0/project/custodes-97a6a/firestore/data/~2Ftest~2FconnMsg), idk how to access it with flutter yet tho lol

**Comment by Yoel1515** [comment]
ya veo tons procedere a ver tutoriales xd

**Comment by 2021030063** [comment]
db connection done successfully, check commit [25ec599](https://github.com/Centinela-RR/Custodes/commit/25ec5994f6a3192bbc987d65ae164384138e2bb4)
Bien pinche alien, pero estoy empezando a entenderle al mismo tiempo que a Dart; it's just so weirddddddd
