### ISSUE TITLE
[ESENCIAL] Enviar y recibir info de la db

### ISSUE THREAD

**Issue by 2021030063** [Centinela-RR/Custodes#21]
Info de la db en Firebase en [#20](https://github.com/Centinela-RR/Custodes/issues/20#issue-2088808600)
Hay que:
- Enviar ~el id del usuario único (#27)~ el número o id del usuario (#32)  a la db al picarle a un botón
- Obtener el mensaje de la db más reciente por predeterminado de la colección "test" y emitirlo en pantalla (ya sea como alerta, modal, o crear un nuevo elemento) al picarle a otro botón

**Comment by Yoel1515** [comment]
esto aun no esta echo vdd?

**Comment by 2021030063** [comment]
nuhuh, hay que limpiar la app principal y dejar un mensaje que al conectarse con la db diga "yea!" o algo, idk
Al picarle a un botón, daría algún mensaje de que escribió, o que recibió info, idk 
El chiste es probar la conexión y la escritura/lectura

**Comment by Yoel1515** [comment]
no se ejecuta la aplicacion en el emulador dice que hay un error en el archivo de build.grandle de android dice que ayer pusiste algo id 'com.google.gms.google-services' version '4.4.0' apply false

**Comment by 2021030063** [comment]
Decía en el tuto de firebase que lo hiciera fml, removing it

**Comment by 2021030063** [comment]
pushed, should work now

**Comment by Yoel1515** [comment]
hay otro al final en Custodes\android\app\build.gradle app linea 69
que sale error

**Comment by 2021030063** [comment]
wtf, firebase tutorials are shit then
### Commented the line, should work and build properly now

**Comment by Yoel1515** [comment]
bañes tremenda lista de errores aparece 
algunas movidas con multidex etc ya lo vere mañana

**Comment by 2021030063** [comment]
flutter clean && flutter pub get && flutter run

A veces me ayuda cuando estoy sufriendo en Xcode 🗡️

**Comment by Yoel1515** [comment]
https://pub.dev/packages/device_info_plus

**Comment by 2021030063** [comment]
QUEDÓ CON EL EMU WOOOO
