### ISSUE TITLE
[VISUAL] Splash-screen

### ISSUE THREAD

**Issue by 2021030063** [Centinela-RR/Custodes#29]
**¿Tu solicitud está relacionada con un componente visual de la aplicación? Por favor, describe cuál es. De lo contrario, escoge otra issue.**
Una descripción clara y concisa del componente visual en cuestión. Por ejemplo: "Diseño del botón de inicio de sesión".

- Implementación programática de la splash-screen 

**Describe cómo agregarías, mejorarías o ajustarías este componente visual.**
Explica qué cambios te gustaría implementar y cómo mejorarían la experiencia del usuario. Por ejemplo: "Mejorar la legibilidad del texto en el botón de inicio de sesión aumentando el tamaño de la fuente".

- Para que se vea bonito el abrir la aplicación, implementar el plugin another_flutter_splash_screen (docs [aquí](https://pub.dev/packages/another_flutter_splash_screen)) con cualquier imagen con un texto sobrepuesto

**¿Has considerado alternativas de diseño?**
Describe otras opciones de diseño que has considerado y por qué has optado por esta solución. Por ejemplo: "Consideré varios estilos de botones, pero opté por este diseño específico porque se alinea mejor con nuestra identidad de marca".

- Ninguna

**Contexto Adicional:**
Añade aquí cualquier otro contexto relevante, capturas de pantalla, mockups o referencias visuales que ayuden a comprender el componente visual y su implementación.

- Ninguno

**Comment by Yoel1515** [comment]
Yo tengo un problema con el splashscreen que osea si funciona pero en lo que es el emulador me sigue apareciendo en blanco predeterminado todo, pero si saco la APK ya sale con los cambios que hice , y es una flojera estar sacando apks asi que lo dejare de paso de momento 
Solo es con la splashcreen ya con otros cambios el hot reload todo normal

**Comment by 2021030063** [comment]
Yoink, listo ;P
