### ISSUE TITLE
Preparar y probar la app en Android Studio

### ISSUE THREAD

**Issue by 2021030063** [Centinela-RR/Custodes#3]
Alguien debería de dedicarse de lleno a la app del lado de Android y si se puede a Windows (no me sale de opción), en Windows también:D
El que decida tomarlo de los devs,  asígnese a esta issue pls kthx

Hay que:
- Poner el nombre de la empresa
- Poner el nombre de la app
- Establecer la versión mínima a utilizar de Android
- Ejecutar la prueba y asegurarse de que no tenga errores, y si hay, corregirlos

**Comment by 2021030063** [comment]
Hay que usar la rama (branch) de app-prealpha, btw*

**Comment by Yoel1515** [comment]
JAJA  pera apenas me voa a poner a estudiar el codigo aver como se come jaja

**Comment by 2021030063** [comment]
No hay necesidad alguna de alterar el código de ninguna manera, sólo es abrir el proyecto generado por flutter de Android Studio y editar las propiedades del proyecto, por lo que te lo encargo, @Yoel1515 ;D

**Comment by Yoel1515** [comment]
eh que wea se elimino la asignacion JAJA

**Comment by Yoel1515** [comment]
yo me encargo de ver como se come lo de android studio

**Comment by 2021030063** [comment]
Asignado then, cualquier cosa reporta aquí o si es grande, en discusiones pls kthx

**Comment by Yoel1515** [comment]
Okey lo estare viendo estos dias

**Comment by 2021030063** [comment]
:)

**Comment by Yoel1515** [comment]
Jajaja y esoooo Felipe nimodo

**Comment by Yoel1515** [comment]
Android studio intalado 
**Flutter SDK [3.16.7]** (https://storage.googleapis.com/flutter_infra_release/releases/stable/windows/flutter_windows_3.16.7-stable.zip)
**Dart SDK [3.2.4]** 

Emulación en proceso

**Comment by Yoel1515** [comment]
Cambios realizados y enviados a **prealpha**
Cambio de nombre 
ID
Y se reviso que funcionará en la emulación
