### ISSUE TITLE
Preparar y probar la app para web

### ISSUE THREAD

**Issue by 2021030063** [Centinela-RR/Custodes#7]
Quizás se termine ignorando al finalizar, pero de todas formas se debería trabajar en ella.
@Fdjcm2 considero que tiene la capacidad para trabajar en ella, pero @JW33D es más que bienvenido jaja

Requiere Chrome o algún navegador basado en Chromium, para más info busquen recursos dentro de la página de documentación de Flutter

**Comment by Fdjcm2** [comment]
Weee

**Comment by 2021030063** [comment]
Si sí te llama la atención trabajar en ella, asígnatela, si no, puedes ayudar a Yoel en #3 y le dejamos esta a @JW33D

**Comment by Fdjcm2** [comment]
Flutter lo permite hacer desde el inició todo al depurar solo debe estar declarado y revisar compatibilidad. Al depurar en VS code te pregunta en qué dispositivo web, Windows, Android. En Andorid hay que instalar los SDK o depurar en el cel directo con USB.

**Comment by JW33D** [comment]
Wey aún no termino de tender está wea de GitHub, pero ahí le checo

**Comment by Fdjcm2** [comment]
En iOS no lo probé por qué soy humilde.

**Comment by 2021030063** [comment]
He aquí la mini-wiki que he hecho, en caso de que la necesites para algo @JW33D: https://github.com/Centinela-RR/Custodes/wiki/Inicio

**Comment by 2021030063** [comment]
Cómo va @Fdjcm2?

**Comment by Fdjcm2** [comment]
En conflicto con mis instalaciones pasadas @2021030063. Ahorita estoy viendo que mugrero tengo por las versiones ya que tengo una vieja y no tengo actualizado el SDK de Android y el c

**Comment by 2021030063** [comment]
Resultados: Aplicación funcionó satisfactoriamente y no hubo errores de consola [ :) ]
